version: '3.7'
services:
  angular-client:
    build:
      context: .
      dockerfile: Dockerfile.angular
    ports:
      - 4200:4200
    volumes:
      - .:/app
  express-server:
    build: express-server
    ports:
      - 3000:3000
